frases = [
    ['positivo', 'Sim'],
    ['positivo', 'positivo'],
    ['negativo', 'Não'],
    ['negativo', 'negativo'],

    ['saudação', 'Oi!'],
    ['saudação', 'Olá!'],
    ['saudação', 'Bom dia!'],
    ['saudação', 'Boa tarde!'],
    ['saudação', 'Boa noite!'],
    ['saudação', 'Oi, tudo bem?'],
    ['saudação', 'Oi, como vai?'],
    ['saudação', 'E aí?'],
    ['saudação', 'Oi, como estão as coisas?'],
    ['saudação', 'Olá, tudo certo?'],
    ['saudação', 'Oi, como está?'],
    ['saudação', 'Oi, tudo tranquilo?'],
    ['saudação', 'Oi, tudo bom?'],
    ['saudação', 'Oi, como você está?'],
    ['saudação', 'Oi, tudo certo?'],
    ['saudação', 'Olá, como vai?'],
    ['saudação', 'Oi, tudo bem por aí?'],
    ['saudação', 'Oi, tudo jóia?'],
    ['saudação', 'E aí, beleza?'],
    ['saudação', 'Oi, tudo em ordem?'],
    ['saudação', 'Olá, como está o dia?'],
    ['saudação', 'Oi, tudo bem com você?'],
    ['saudação', 'E aí, tudo tranquilo?'],
    ['saudação', 'Oi, tudo em paz?'],
    ['saudação', 'Oi, como estão as coisas por aí?'],
    ['saudação', 'Oi, como vai você?'],
    ['saudação', 'Oi, tudo legal?'],
    ['saudação', 'Oi, como está indo?'],
    ['saudação', 'Oi, tudo certo contigo?'],
    ['saudação', 'Oi, como estão as coisas?'],

    ['descrição de problema', 'bateria', 'O carro só liga se eu der uma carga rápida na bateria.'],
    ['descrição de problema', 'bateria', 'As luzes acendem, mas o motor não vira.'],
    ['descrição de problema', 'bateria', 'O sistema elétrico está estranho, os faróis estão piscando sozinhos.'],
    ['descrição de problema', 'bateria', 'Ouço um clique repetido quando tento ligar o carro.'],
    ['descrição de problema', 'bateria', 'A bateria parece estar fraca, o rádio falha constantemente.'],
    ['descrição de problema', 'bateria', 'O carro apaga do nada enquanto estou dirigindo, e não liga de novo.'],
    ['descrição de problema', 'bateria', 'As luzes do painel piscam e depois se apagam quando giro a chave.'],
    ['descrição de problema', 'bateria', 'Deixei o carro parado por alguns dias e agora ele não liga.'],
    ['descrição de problema', 'bateria', 'A luz da bateria acende quando uso o ar-condicionado.'],
    ['descrição de problema', 'bateria', 'O motor está girando, mas não tem energia suficiente para ligar.'],
    ['descrição de problema', 'bateria', 'Sinto que o carro perde potência quando os faróis estão acesos.'],
    ['descrição de problema', 'bateria', 'A bateria descarrega toda vez que uso os limpadores de para-brisa.'],
    ['descrição de problema', 'bateria', 'O carro vibra quando tento ligar e depois morre.'],
    ['descrição de problema', 'bateria', 'Ouço um estalo e as luzes piscam quando tento ligar o carro.'],
    ['descrição de problema', 'bateria', 'O motor começa a funcionar, mas morre logo em seguida.'],
    ['descrição de problema', 'bateria', 'Tentei trocar a bateria, mas o problema persiste.'],
    ['descrição de problema', 'bateria', 'O carro parece sem energia quando tento usar os controles internos.'],
    ['descrição de problema', 'bateria', 'Toda vez que paro no semáforo, o carro desliga sozinho.'],
    ['descrição de problema', 'bateria', 'O carregador portátil só dá uma carga parcial antes de desligar.'],
    ['descrição de problema', 'bateria', 'O carro só responde após várias tentativas de ligar a chave.'],
    ['descrição de problema', 'bateria', 'Acho que o carro está descarregado, não consigo ligá-lo.'],
    ['descrição de problema', 'bateria', 'As luzes do painel nem acendem quando tento dar partida.'],
    ['descrição de problema', 'bateria', 'O carro ficou parado muito tempo e agora não liga mais.'],
    ['descrição de problema', 'bateria', 'O carro não liga de manhã, parece que está sem força.'],
    ['descrição de problema', 'bateria', 'O carro não quer pegar de jeito nenhum.'],
    ['descrição de problema', 'bateria', 'O motor não dá nem sinal de vida.'],
    ['descrição de problema', 'bateria', 'Parece que o carro está sem energia.'],
    ['descrição de problema', 'bateria', 'Preciso dar uma carga no carro para ele ligar.'],
    ['descrição de problema', 'bateria', 'Preciso de um cabo para dar partida no carro.'],
    ['descrição de problema', 'bateria', 'Quando giro a chave, o motor só faz um clique e nada acontece.'],
    ['descrição de problema', 'bateria', 'O carro não liga depois que deixei os faróis acesos por muito tempo.'],
    ['descrição de problema', 'bateria', 'O rádio funciona, mas o motor não responde ao tentar ligar.'],
    ['descrição de problema', 'bateria', 'A bateria foi trocada recentemente, mas o carro não liga.'],
    ['descrição de problema', 'bateria', 'O carro não liga quando faz frio, parece que a bateria está fraca.'],
    ['descrição de problema', 'bateria', 'O painel pisca, mas o carro não dá partida.'],
    ['descrição de problema', 'bateria', 'Tentei várias vezes, mas o motor não gira, acho que é a bateria.'],
    ['descrição de problema', 'bateria', 'Parece que a bateria morreu, o carro não responde.'],
    ['descrição de problema', 'bateria', 'A luz da bateria está acesa no painel e o carro está estranho.'],
    ['descrição de problema', 'bateria', 'O carro só liga com a ajuda de um carregador portátil.'],
    ['descrição de problema', 'bateria', 'O carro demora muito para pegar, mesmo quando tento várias vezes.'],
    ['descrição de problema', 'bateria', 'Quando giro a chave, as luzes piscam, mas o motor não liga.'],
    ['descrição de problema', 'bateria', 'A bateria parece nova, mas o carro não responde.'],
    ['descrição de problema', 'bateria', 'O sistema elétrico parece funcionar, mas o motor não liga.'],
    ['descrição de problema', 'bateria', 'Preciso sempre de um empurrão para o carro pegar.'],
    ['descrição de problema', 'bateria', 'O carro perde força quando ligo o ar-condicionado.'],
    ['descrição de problema', 'bateria', 'A luz da bateria no painel está piscando intermitentemente.'],
    ['descrição de problema', 'bateria', 'O motor demora para responder, principalmente pela manhã.'],
    ['descrição de problema', 'bateria', 'O carro não liga após várias tentativas, mesmo com carga suficiente.'],
    ['descrição de problema', 'bateria', 'A bateria descarrega rápido quando uso dispositivos no carro.'],
    ['descrição de problema', 'bateria', 'As portas travam sozinhas e o carro não dá partida.'],
    ['descrição de problema', 'bateria', 'O carro morre no trânsito e não consigo ligá-lo de novo.'],
    ['descrição de problema', 'bateria', 'Tentei carregar a bateria, mas não segurou a carga.'],
    ['descrição de problema', 'bateria', 'As luzes internas do carro piscam quando tento ligá-lo.'],
    ['descrição de problema', 'bateria', 'O painel fica completamente apagado quando tento ligar o carro.'],
    ['descrição de problema', 'bateria', 'A bateria parece estar fraca, mas os componentes eletrônicos funcionam.'],
    ['descrição de problema', 'bateria', 'O rádio reinicia sozinho quando tento ligar o carro.'],
    ['descrição de problema', 'bateria', 'O carro não responde mesmo com os faróis funcionando.'],
    ['descrição de problema', 'bateria', 'Precisei trocar a bateria, mas o problema persiste.'],
    ['descrição de problema', 'bateria', 'O carro desliga sozinho no meio do caminho.'],
    ['descrição de problema', 'bateria', 'O sistema de ignição parece falhar repetidamente.'],
    ['descrição de problema', 'bateria', 'Mesmo com a bateria nova, o carro não liga corretamente.'],
    ['descrição de problema', 'bateria', 'A bateria esquenta muito quando tento dar partida.'],
    ['descrição de problema', 'bateria', 'A luz de emergência acendeu e o carro não responde.'],
    ['descrição de problema', 'bateria', 'O carro só pega se deixo a chave na ignição por um tempo.'],
    ['descrição de problema', 'bateria', 'A bateria descarrega quando deixo o rádio ligado por pouco tempo.'],
    ['descrição de problema', 'bateria', 'A chave não responde, o carro parece sem energia.'],
    ['descrição de problema', 'bateria', 'O motor dá sinais de vida, mas logo morre novamente.'],
    ['descrição de problema', 'bateria', 'O carro vibra quando tento ligá-lo, mas não dá partida.'],
    
    ['descrição de problema', 'motor', 'O carro começa a engasgar quando passo de 60 km/h.'],
    ['descrição de problema', 'motor', 'Sinto que o carro perde força ao tentar subir morros.'],
    ['descrição de problema', 'motor', 'O carro falha ao tentar manter uma velocidade constante.'],
    ['descrição de problema', 'motor', 'Ouço um barulho agudo vindo do motor quando acelero.'],
    ['descrição de problema', 'motor', 'O motor faz um som de explosão quando estou dirigindo rápido.'],
    ['descrição de problema', 'motor', 'O carro parece "pular" quando acelero rapidamente.'],
    ['descrição de problema', 'motor', 'O motor esquenta muito rápido em viagens curtas.'],
    ['descrição de problema', 'motor', 'O carro demora muito para pegar depois de ficar parado um tempo.'],
    ['descrição de problema', 'motor', 'Sinto uma trepidação forte no volante ao acelerar.'],
    ['descrição de problema', 'motor', 'O motor faz um som estranho quando ligo o ar-condicionado.'],
    ['descrição de problema', 'motor', 'Há um ruído metálico quando desacelero o carro rapidamente.'],
    ['descrição de problema', 'motor', 'O carro perde força toda vez que troco de marcha.'],
    ['descrição de problema', 'motor', 'O motor continua a girar mesmo depois que desligo o carro.'],
    ['descrição de problema', 'motor', 'Ouço um barulho oco vindo do motor em rotações baixas.'],
    ['descrição de problema', 'motor', 'Sinto uma vibração no banco do motorista quando acelero.'],
    ['descrição de problema', 'motor', 'O motor parece estar trabalhando muito pesado mesmo em baixa rotação.'],
    ['descrição de problema', 'motor', 'O carro faz um barulho de chiado quando acelero devagar.'],
    ['descrição de problema', 'motor', 'O carro dá trancos quando passo dos 80 km/h.'],
    ['descrição de problema', 'motor', 'Sinto uma perda de potência considerável ao tentar ultrapassar outros carros.'],
    ['descrição de problema', 'motor', 'O motor faz um som alto de batida ao tentar dar a partida.'],
    ['descrição de problema', 'motor', 'A luz de alerta acendeu no painel, e o carro está rodando estranho.'],
    ['descrição de problema', 'motor', 'Ele está demorando muito para responder quando piso no acelerador.'],
    ['descrição de problema', 'motor', 'O carro está perdendo potência nas subidas.'],
    ['descrição de problema', 'motor', 'O carro morre do nada enquanto estou dirigindo.'],
    ['descrição de problema', 'motor', 'Ouço um barulho estranho vindo da frente do carro.'],
    ['descrição de problema', 'motor', 'Parece que o carro está engasgando ao rodar.'],
    ['descrição de problema', 'motor', 'Sinto trepidações ao acelerar.'],
    ['descrição de problema', 'motor', 'Sinto um cheiro forte de algo queimando quando dirijo.'],
    ['descrição de problema', 'motor', 'O carro faz barulhos estranhos quando acelero rapidamente.'],
    ['descrição de problema', 'motor', 'O motor parece estar "engasgando" ao tentar ganhar velocidade.'],
    ['descrição de problema', 'motor', 'Ouço ruídos metálicos vindos do motor ao subir ladeiras.'],
    ['descrição de problema', 'motor', 'O carro está falhando quando acelero.'],
    ['descrição de problema', 'motor', 'O carro parece estar perdendo força ao atingir altas velocidades.'],
    ['descrição de problema', 'motor', 'O motor está esquentando demais, parece que algo está errado.'],
    ['descrição de problema', 'motor', 'O carro perde força ao trocar de marcha.'],
    ['descrição de problema', 'motor', 'Ouço um som de batida vindo do motor quando acelero.'],
    ['descrição de problema', 'motor', 'O carro está vibrando mais do que o normal, especialmente no motor.'],
    ['descrição de problema', 'motor', 'O motor parece estar trabalhando pesado, mesmo quando não acelero muito.'],
    ['descrição de problema', 'motor', 'O motor faz um som alto ao atingir altas velocidades.'],
    ['descrição de problema', 'motor', 'O motor parece estar engasgando em baixas rotações.'],
    ['descrição de problema', 'motor', 'O carro está perdendo força ao tentar acelerar em subidas.'],
    ['descrição de problema', 'motor', 'Sinto um cheiro de combustível quando o motor está ligado.'],
    ['descrição de problema', 'motor', 'O motor treme quando ligo o carro pela primeira vez no dia.'],
    ['descrição de problema', 'motor', 'O carro acelera sozinho às vezes.'],
    ['descrição de problema', 'motor', 'Sinto como se o carro estivesse engasgando quando estou parado.'],
    ['descrição de problema', 'motor', 'O carro desliga sozinho quando está em ponto morto.'],
    ['descrição de problema', 'motor', 'O motor não responde bem ao alternar entre marchas.'],
    ['descrição de problema', 'motor', 'O motor falha repetidamente quando tento manter uma velocidade constante.'],
    ['descrição de problema', 'motor', 'O carro faz um barulho de explosão ao acelerar.'],
    ['descrição de problema', 'motor', 'Sinto uma vibração intensa quando o carro atinge altas rotações.'],
    ['descrição de problema', 'motor', 'O motor tem dificuldade em manter a marcha lenta.'],
    ['descrição de problema', 'motor', 'O carro dá solavancos ao tentar acelerar em ladeiras.'],
    ['descrição de problema', 'motor', 'Há um forte cheiro de óleo queimado após dirigir por muito tempo.'],
    ['descrição de problema', 'motor', 'O motor parece trabalhar mais do que o necessário em subidas leves.'],
    ['descrição de problema', 'motor', 'O carro perde velocidade mesmo com o acelerador totalmente pressionado.'],
    ['descrição de problema', 'motor', 'O motor parece gritar quando estou a 60 km/h.'],
    ['descrição de problema', 'motor', 'O carro consome muito combustível mesmo em pequenas viagens.'],
    ['descrição de problema', 'motor', 'O motor demora a responder quando faço mudanças rápidas de marcha.'],
    ['descrição de problema', 'motor', 'O carro não consegue manter uma rotação estável.'],
    ['descrição de problema', 'motor', 'Ouço um estalo metálico ao passar por buracos.'],
    ['descrição de problema', 'motor', 'O carro desacelera sozinho em estradas planas.'],
    ['descrição de problema', 'motor', 'O motor demora a desligar completamente quando giro a chave.'],
    ['descrição de problema', 'motor', 'Há um atraso considerável entre o pisar no acelerador e a resposta do carro.'],
    ['descrição de problema', 'motor', 'O motor parece "grilar" quando estou a baixas velocidades.'],
    ['descrição de problema', 'motor', 'O carro está sem força para acelerar em estradas longas.'],
    ['descrição de problema', 'motor', 'O motor tem um funcionamento irregular, às vezes falha.'],
    ['descrição de problema', 'motor', 'O carro esquenta rapidamente em viagens curtas.'],
    ['descrição de problema', 'motor', 'O motor está emitindo um ruído agudo constante ao rodar.'],

    ['descrição de problema', 'suspensao', 'O carro está afundando na frente quando freio bruscamente.'],
    ['descrição de problema', 'suspensao', 'O volante vibra muito em ruas esburacadas.'],
    ['descrição de problema', 'suspensao', 'O carro parece estar balançando mais que o normal em curvas fechadas.'],
    ['descrição de problema', 'suspensao', 'Há um rangido contínuo quando o carro está em movimento.'],
    ['descrição de problema', 'suspensao', 'Sinto que o carro está mais baixo de um lado do que do outro.'],
    ['descrição de problema', 'suspensao', 'Ouço um som de batida seca quando passo por lombadas.'],
    ['descrição de problema', 'suspensao', 'O carro oscila muito quando estou em uma estrada plana.'],
    ['descrição de problema', 'suspensao', 'Há um barulho metálico vindo da suspensão traseira.'],
    ['descrição de problema', 'suspensao', 'Sinto o carro sacudir toda vez que passo por uma pequena ondulação.'],
    ['descrição de problema', 'suspensao', 'As rodas fazem um som de raspagem quando viro o volante completamente.'],
    ['descrição de problema', 'suspensao', 'O carro parece estar sem estabilidade em altas velocidades.'],
    ['descrição de problema', 'suspensao', 'Sinto o carro inclinar demais ao frear bruscamente.'],
    ['descrição de problema', 'suspensao', 'Ouço um estalo forte ao passar por lombadas e buracos.'],
    ['descrição de problema', 'suspensao', 'A frente do carro bate facilmente no chão ao passar por declives.'],
    ['descrição de problema', 'suspensao', 'O carro faz um barulho de ranger constante quando dirijo em ruas de paralelepípedo.'],
    ['descrição de problema', 'suspensao', 'O carro parece balançar como um barco quando estou em uma estrada reta.'],
    ['descrição de problema', 'suspensao', 'As rodas parecem estar desalinhadas, o volante está puxando para um lado.'],
    ['descrição de problema', 'suspensao', 'Ouço um barulho de "thump" ao passar por um pequeno buraco.'],
    ['descrição de problema', 'suspensao', 'O carro está oscilando muito mesmo em velocidades moderadas.'],
    ['descrição de problema', 'suspensao', 'A traseira do carro está batendo muito ao passar por valetas.'],
    ['descrição de problema', 'suspensao', 'A frente do carro está mais baixa que o normal.'],
    ['descrição de problema', 'suspensao', 'Está difícil controlar o carro em alta velocidade.'],
    ['descrição de problema', 'suspensao', 'O carro bate seco quando passa por lombadas.'],
    ['descrição de problema', 'suspensao', 'O carro está fazendo um barulho estranho quando passa por buracos.'],
    ['descrição de problema', 'suspensao', 'O carro está inclinando muito para um lado nas curvas.'],
    ['descrição de problema', 'suspensao', 'O carro pula muito quando passo por ruas irregulares.'],
    ['descrição de problema', 'suspensao', 'Ouço um rangido vindo das rodas quando freio.'],
    ['descrição de problema', 'suspensao', 'Parece que o carro está balançando demais ao dirigir.'],
    ['descrição de problema', 'suspensao', 'Sinto o carro meio solto nas curvas.'],
    ['descrição de problema', 'suspensao', 'A traseira do carro está fazendo barulhos ao passar por buracos.'],
    ['descrição de problema', 'suspensao', 'O carro está instável ao rodar em altas velocidades.'],
    ['descrição de problema', 'suspensao', 'Ouço um barulho metálico quando passo por ruas irregulares.'],
    ['descrição de problema', 'suspensao', 'Sinto o carro mais baixo de um lado do que do outro.'],
    ['descrição de problema', 'suspensao', 'O carro está com dificuldade de passar por lombadas sem bater.'],
    ['descrição de problema', 'suspensao', 'Há um rangido constante ao dirigir em estradas esburacadas.'],
    ['descrição de problema', 'suspensao', 'Sinto o volante "puxar" para um dos lados ao dirigir.'],
    ['descrição de problema', 'suspensao', 'O carro está fazendo um barulho de estalo quando acelero.'],
    ['descrição de problema', 'suspensao', 'O carro está com uma inclinação estranha nas curvas.'],
    ['descrição de problema', 'suspensao', 'Ouço um estalo metálico ao fazer curvas.'],
    ['descrição de problema', 'suspensao', 'O carro está difícil de controlar em pisos irregulares.'],
    ['descrição de problema', 'suspensao', 'A frente do carro parece muito baixa quando freio.'],
    ['descrição de problema', 'suspensao', 'Há um barulho de batida vindo de baixo quando passo por buracos.'],
    ['descrição de problema', 'suspensao', 'O carro parece estar dançando ao dirigir em alta velocidade.'],
    ['descrição de problema', 'suspensao', 'As rodas da frente estão fazendo um barulho metálico quando viro o volante.'],
    ['descrição de problema', 'suspensao', 'Sinto um barulho de metal batendo quando passo por lombadas.'],
    ['descrição de problema', 'suspensao', 'Ouço um rangido ao girar o volante completamente.'],
    ['descrição de problema', 'suspensao', 'O carro parece estar "saltando" ao passar por buracos.'],
    ['descrição de problema', 'suspensao', 'O carro está muito inclinado quando passo por curvas.'],
    ['descrição de problema', 'suspensao', 'Há uma vibração nas rodas ao passar por terrenos irregulares.'],
    ['descrição de problema', 'suspensao', 'O carro está inclinado, com a traseira mais alta.'],

    ['descrição de problema', 'freios', 'O carro demora mais do que o normal para parar.'],
    ['descrição de problema', 'freios', 'Ouço um som de raspagem quando piso no freio.'],
    ['descrição de problema', 'freios', 'O pedal do freio está muito mole, parece afundar.'],
    ['descrição de problema', 'freios', 'Sinto o pedal do freio vibrar quando pressiono.'],
    ['descrição de problema', 'freios', 'O carro puxa para um dos lados quando freio.'],
    ['descrição de problema', 'freios', 'Ouço um chiado alto ao acionar os freios.'],
    ['descrição de problema', 'freios', 'O carro treme quando freio em altas velocidades.'],
    ['descrição de problema', 'freios', 'Os freios fazem barulho metálico ao serem acionados.'],
    ['descrição de problema', 'freios', 'O pedal do freio está muito duro, quase não consigo pressionar.'],
    ['descrição de problema', 'freios', 'Há um cheiro de queimado quando uso os freios repetidamente.'],
    ['descrição de problema', 'freios', 'Os freios fazem um barulho de raspagem quando acionados.'],
    ['descrição de problema', 'freios', 'O freio de mão parece não estar segurando bem.'],
    ['descrição de problema', 'freios', 'O carro treme muito ao frear em baixa velocidade.'],
    ['descrição de problema', 'freios', 'Sinto que o carro está deslizando ao frear bruscamente.'],
    ['descrição de problema', 'freios', 'O pedal do freio vai até o fundo sem resistência.'],
    ['descrição de problema', 'freios', 'Ouço um estalo forte quando aciono o freio bruscamente.'],
    ['descrição de problema', 'freios', 'O freio parece solto, precisa de muita força para parar o carro.'],
    ['descrição de problema', 'freios', 'Há um som de chiado quando piso levemente no freio.'],
    ['descrição de problema', 'freios', 'O carro dá solavancos ao frear.'],
    ['descrição de problema', 'freios', 'O carro continua a se mover mesmo com o pedal totalmente pressionado.'],
    ['descrição de problema', 'freios', 'O carro freia de forma irregular, parece "saltar" ao parar.'],
    ['descrição de problema', 'freios', 'Ouço um estalo metálico quando piso no freio com força.'],
    ['descrição de problema', 'freios', 'Sinto o pedal do freio tremer quando freio em descidas.'],
    ['descrição de problema', 'freios', 'Os freios estão mais fracos do que o normal, parece que não seguram bem.'],
    ['descrição de problema', 'freios', 'O freio não responde imediatamente quando pressiono o pedal.'],
    ['descrição de problema', 'freios', 'Ouço um barulho metálico forte quando freio em alta velocidade.'],
    ['descrição de problema', 'freios', 'O pedal do freio desce muito rápido, parece que está sem pressão.'],
    ['descrição de problema', 'freios', 'Os freios demoram para responder ao pressionar o pedal.'],
    ['descrição de problema', 'freios', 'Ouço um som de arranhado vindo das rodas ao frear.'],
    ['descrição de problema', 'freios', 'O pedal do freio vibra em altas velocidades, especialmente em curvas.'],
    ['descrição de problema', 'freios', 'Ouço um som de assobio constante toda vez que piso no freio.'],
    ['descrição de problema', 'freios', 'O pedal do freio parece mais duro que o normal.'],
    ['descrição de problema', 'freios', 'Sinto uma trepidação forte no volante quando freio bruscamente.'],
    ['descrição de problema', 'freios', 'O carro demora mais para parar quando estou em alta velocidade.'],
    ['descrição de problema', 'freios', 'Há um som de "clique" toda vez que piso no freio.'],
    ['descrição de problema', 'freios', 'Os freios estão fazendo um chiado alto ao descer uma ladeira.'],
    ['descrição de problema', 'freios', 'O carro derrapa mesmo em baixa velocidade quando freio.'],
    ['descrição de problema', 'freios', 'O pedal do freio parece estar raspando no fundo.'],
    ['descrição de problema', 'freios', 'Há uma vibração nas rodas quando aciono os freios em altas velocidades.'],
    ['descrição de problema', 'freios', 'Os freios estão fazendo um barulho de metal raspando constantemente.'],
    ['descrição de problema', 'freios', 'Ouço um som de estalo toda vez que solto o pedal do freio.'],
    ['descrição de problema', 'freios', 'O freio está demorando para responder, mesmo com o pedal pressionado.'],
    ['descrição de problema', 'freios', 'O carro dá uma "pulada" ao parar completamente.'],
    ['descrição de problema', 'freios', 'O freio não responde bem quando estou em descidas.'],
    ['descrição de problema', 'freios', 'Ouço um som de ranger constante ao acionar os freios.'],
    ['descrição de problema', 'freios', 'O pedal do freio parece afundar completamente sem resistência.'],
    ['descrição de problema', 'freios', 'Há um barulho forte quando piso no freio de emergência.'],
    ['descrição de problema', 'freios', 'Sinto uma vibração no banco quando freio bruscamente.'],
    ['descrição de problema', 'freios', 'Os freios fazem um som de "estalo" quando usados repetidamente.'],
    ['descrição de problema', 'freios', 'O carro puxa bruscamente para um lado quando piso no freio.']
]

problemas_freios = [
    ["Pastilhas de freio gastas", "troca de pastilha", 200],
    ["Discos de freio desgastados", "troca de discos", 400],
    ["Ruído ao acionar os freios", "verificação e ajuste de freios", 150],
    ["Pedal de freio duro ou sem resposta", "ajuste do sistema de freios", 250],
    ["Vazamento de fluido de freio", "troca de fluido e reparo de vazamento", 180],
    ["Freios travando ou vibrando", "ajuste e verificação do sistema de freios", 220],
    ["Freios com perda de eficiência", "troca de fluido e revisão completa", 300],
    ["Freios esquentando após uso prolongado", "verificação e resfriamento dos freios", 250],
    ["Pedal de freio baixo", "ajuste de freios e troca de fluido", 230],
    ["Sistema ABS falhando", "reparo ou substituição do sistema ABS", 800],
    ["Luz de alerta dos freios no painel", "diagnóstico do sistema de freios", 200],
    ["Freios rangendo em baixa velocidade", "limpeza e ajuste das pastilhas de freio", 180],
    ["Pedal de freio trepidando ao acionar", "verificação dos discos de freio", 220],
    ["Freio a tambor travando", "ajuste e lubrificação do freio a tambor", 210],
    ["Ruído de arranhado ao frear", "substituição de pastilhas de freio", 250],
    ["Pedal de freio com excesso de folga", "ajuste do sistema de freios", 230],
    ["Freios com superaquecimento frequente", "troca de discos de freio ventilados", 450],
    ["Vibração no volante ao frear", "retífica dos discos de freio", 300],
    ["Desgaste irregular nas pastilhas de freio", "verificação das pinças de freio", 280],
    ["Freios acionando sozinhos", "verificação do cilindro mestre", 350],
    ["Perda de pressão no pedal do freio", "reparo do cilindro mestre", 400],
    ["Freio de mão com folga", "ajuste do freio de mão", 150],
    ["Travamento das rodas ao frear", "reparo do sistema ABS", 700],
    ["Ruído de metal ao metal nos freios", "troca de discos e pastilhas de freio", 500],
    ["Freios com excesso de ruído ao molhado", "troca de pastilhas e discos anti-ruído", 400],
    ["Freio acionando de forma intermitente", "verificação dos sensores ABS", 350],
    ["Luz de freio piscando no painel", "diagnóstico completo do sistema de freios", 300],
    ["Freio de mão não segura o carro", "substituição do cabo do freio de mão", 200],
    ["Pedal de freio com pulsação", "verificação dos rotores de freio", 280],
    ["Freios sensíveis demais", "ajuste do servo freio", 250],
    ["Freios desgastados rapidamente", "inspeção da linha de fluido de freio", 320],
    ["Barulho metálico ao pressionar o freio", "verificação das pinças e pastilhas", 290],
    ["Freios arrastando mesmo sem acionar", "reparação das pinças de freio", 400],
    ["Falha completa do freio ao pisar", "reparo ou troca do cilindro mestre", 600],
    ["Ruído contínuo durante a frenagem", "troca das pastilhas de freio", 240],
    ["Falta de resposta imediata ao frear", "ajuste do cilindro mestre", 280],
    ["Desgaste irregular nas pastilhas de freio", "inspeção e substituição das pastilhas", 260],
    ["Trechos longos sem resposta dos freios", "reparo do sistema hidráulico de freio", 320],
    ["Pedal de freio com excesso de folga", "ajuste no curso do pedal de freio", 230]
]

problemas_suspensao = [
    ["Amortecedores desgastados", "troca de amortecedores", 600],
    ["Ruídos ao passar em lombadas", "verificação de molas e amortecedores", 250],
    ["Veículo puxando para um lado", "alinhamento e balanceamento", 150],
    ["Suspensão muito dura ou macia", "verificação da suspensão e ajuste", 350],
    ["Estabilidade comprometida em curvas", "troca de componentes da suspensão", 500],
    ["Desgaste irregular dos pneus", "alinhamento e verificação da suspensão", 180],
    ["Vazamento de óleo nos amortecedores", "troca de amortecedores", 600],
    ["Barulho metálico ao virar o volante", "verificação das juntas homocinéticas", 400],
    ["Suspensão traseira mais baixa que a dianteira", "substituição de molas ou amortecedores traseiros", 500],
    ["Oscilação ao frear", "verificação da suspensão e geometria", 300],
    ["Carro quicando demais em estradas irregulares", "revisão completa da suspensão", 450],
    ["Batidas secas ao passar por buracos", "verificação das buchas da suspensão", 350],
    ["Vibrações na direção", "balanceamento e alinhamento", 200],
    ["Suspensão com folga", "troca de pivôs e terminais de direção", 400],
    ["Veículo balançando excessivamente", "troca dos amortecedores", 700],
    ["Carro com altura desigual", "substituição das molas", 500],
    ["Ruído na suspensão ao esterçar", "verificação das buchas de bandeja", 250],
    ["Desgaste anormal de pneus", "alinhamento completo", 180],
    ["Suspensão com vazamento de óleo", "troca dos amortecedores hidráulicos", 650],
    ["Folga na direção", "troca de terminais de direção", 300],
    ["Estalos ao passar por buracos", "reparo das bandejas da suspensão", 400],
    ["Suspensão traseira batendo", "substituição dos batentes da suspensão", 350],
    ["Suspensão com ruído ao carregar peso", "verificação das molas e amortecedores", 300],
    ["Suspensão abaixando sozinha", "diagnóstico detalhado e troca de molas", 450],
    ["Oscilação ao fazer curvas", "verificação e ajuste da barra estabilizadora", 320],
    ["Balanço excessivo em terrenos irregulares", "revisão da suspensão completa", 500],
    ["Amortecedor com folga", "troca de buchas e pivôs", 380],
    ["Barulho ao virar o volante em baixa velocidade", "verificação da caixa de direção", 400],
    ["Vibração excessiva no volante", "balanceamento e alinhamento", 200],
    ["Suspensão dianteira mais alta que a traseira", "substituição de amortecedores traseiros", 600],
    ["Suspensão ruidosa ao frear", "inspeção e reparo das buchas da suspensão", 350],
    ["Estalos constantes na suspensão", "substituição das juntas homocinéticas", 500],
    ["Suspensão traseira solta", "substituição de molas ou amortecedores traseiros", 550],
    ["Barulho de batida seca ao passar em lombadas", "verificação e troca das buchas", 360],
    ["Suspensão fazendo ruídos metálicos", "revisão das buchas da suspensão", 400],
    ["Oscilação do veículo após passar por obstáculos", "ajuste da suspensão", 370],
    ["Suspensão traseira baixa após carga excessiva", "substituição das molas traseiras", 450],
    ["Pneus desgastados irregularmente", "balanceamento e alinhamento da suspensão", 180],
    ["Vibração constante no volante ao dirigir", "revisão dos amortecedores", 300]
]

problemas_motor = [
    ["Falta de potência no motor", "diagnóstico detalhado e ajuste do motor", 400],
    ["Consumo excessivo de combustível", "verificação da injeção eletrônica", 300],
    ["Ruídos anormais no motor", "diagnóstico detalhado de componentes internos", 450],
    ["Motor superaquecendo", "reparo no radiador ou troca de termostato", 350],
    ["Dificuldade para dar partida", "troca de velas ou cabos", 250],
    ["Vazamento de óleo do motor", "troca de juntas e vedação", 400],
    ["Fumaça excessiva saindo do escapamento", "verificação de anéis e pistões", 500],
    ["Fumaça branca saindo do escapamento", "verificação de junta do cabeçote", 600],
    ["Motor desligando sozinho", "diagnóstico do sistema de ignição", 350],
    ["Cheiro de gasolina no interior do carro", "verificação de vazamento de combustível", 250],
    ["Motor batendo ao acelerar", "diagnóstico de pistões ou bielas", 700],
    ["Perda de aceleração ao subir ladeiras", "verificação de bomba de combustível", 300],
    ["Motor falhando em baixa rotação", "troca de sensor de rotação", 450],
    ["Trepidação excessiva do motor", "troca dos coxins do motor", 500],
    ["Motor apagando em marcha lenta", "ajuste da injeção eletrônica", 400],
    ["Ruído ao ligar o motor a frio", "verificação das velas de ignição", 250],
    ["Perda de potência ao acelerar", "reparação da bomba de combustível", 350],
    ["Vibração excessiva do motor em marcha lenta", "substituição dos coxins", 480],
    ["Fumaça preta saindo do escapamento", "ajuste da mistura de ar e combustível", 450],
    ["Motor com falhas ao atingir alta rotação", "troca de bobinas de ignição", 350],
    ["Motor demorando para aquecer", "verificação do sistema de arrefecimento", 300],
    ["Luz do motor acesa no painel", "diagnóstico eletrônico", 200],
    ["Baixa compressão em um cilindro", "reparo ou troca de anéis", 700],
    ["Motor superaquecendo rapidamente", "substituição do radiador", 800],
    ["Vazamento de água do motor", "reparo de junta ou mangueiras", 350],
    ["Barulho de válvula no motor", "ajuste ou substituição de tuchos", 600],
    ["Cheiro forte de óleo queimado", "verificação do sistema de lubrificação", 300],
    ["Perda de potência ao engatar marchas", "verificação do câmbio e motor", 450],
    ["Motor engasgando ao acelerar", "troca de filtro de combustível", 180],
    ["Trepidação ao ligar o motor", "verificação dos coxins do motor", 500],
    ["Fumaça azul no escapamento", "verificação de consumo de óleo", 600],
    ["Queda de rotação ao frear", "verificação da válvula de controle de ar", 400],
    ["Estalos ao ligar o motor", "substituição de correia dentada", 500],
    ["Motor vibrando excessivamente em altas velocidades", "balanceamento de componentes do motor", 550],
    ["Motor trepidando ao acelerar", "verificação dos coxins", 380],
    ["Vazamento de óleo constante no motor", "troca de juntas e selos", 420],
    ["Motor apresentando falhas em alta rotação", "ajuste da injeção eletrônica", 300],
    ["Cheiro forte de combustível no habitáculo", "verificação de vazamento no sistema de combustível", 340],
    ["Dificuldade em manter o motor em marcha lenta", "ajuste no sistema de injeção", 280]
]

problemas_bateria = [
    ["Bateria descarregando rapidamente", "troca de bateria", 400],
    ["Luzes do painel fracas ao ligar o carro", "recarregamento ou troca de bateria", 350],
    ["Dificuldade ao dar partida no veículo", "troca de bateria", 400],
    ["Oxidação nos terminais da bateria", "limpeza dos terminais", 100],
    ["Bateria com carga insuficiente", "troca de bateria", 400],
    ["Sinal de alerta da bateria no painel", "verificação do sistema elétrico", 200],
    ["Bateria não segura carga", "troca de bateria", 400],
    ["Bateria inchada", "troca imediata de bateria", 450],
    ["Bateria com mal contato", "ajuste nos conectores da bateria", 150],
    ["Carregador da bateria não funcionando", "troca do alternador ou regulador de voltagem", 700],
    ["Bateria com falha intermitente", "verificação do sistema elétrico e substituição de cabos", 300],
    ["Queda de tensão repentina ao dar partida", "verificação do regulador de voltagem", 250],
    ["Carro desliga após retirada dos cabos da bateria", "troca do alternador", 600],
    ["Luz de bateria acesa durante o uso", "verificação da correia do alternador", 200],
    ["Bateria descarrega após poucas horas de uso", "verificação do alternador", 500],
    ["Ruído ao tentar ligar o carro", "substituição da bateria", 400],
    ["Carro morre ao retirar cabos da bateria", "reparo no sistema de carga", 350],
    ["Bateria fica fraca ao usar o ar condicionado", "ajuste no sistema elétrico", 300],
    ["Faróis enfraquecendo com o carro ligado", "verificação do regulador de tensão", 250],
    ["Descarregamento rápido ao usar acessórios", "diagnóstico do sistema elétrico", 400],
    ["Alternador não carrega a bateria", "substituição do alternador", 700],
    ["Bateria fervendo", "revisão do regulador de voltagem", 450],
    ["Bateria de reserva não funciona", "troca da bateria de reserva", 180],
    ["Bateria nova não mantém carga", "verificação do sistema de aterramento", 250],
    ["Dificuldade de partida em dias frios", "verificação da bateria", 200],
    ["Luzes internas piscando", "diagnóstico do sistema elétrico", 300],
    ["Bateria demora a carregar", "verificação do alternador", 400],
    ["Sistema start-stop não funcionando", "verificação da bateria", 350],
    ["Perda de potência elétrica ao acionar faróis", "reparação do sistema elétrico", 300],
    ["Radio desliga ao dar partida", "verificação da bateria e cabos", 150],
    ["Carro desligando ao ficar parado", "verificação da bateria e alternador", 500],
    ["Cabos de bateria superaquecidos", "substituição dos cabos", 250],
    ["Falha intermitente de componentes elétricos", "revisão completa do sistema elétrico", 500],
    ["Avaria no conector da bateria", "substituição do conector", 200],
    ["Bateria desgastada após vários anos de uso", "troca de bateria", 400],
    ["Bateria com problemas recorrentes de carga", "troca de bateria com diagnóstico elétrico", 450],
    ["Bateria incapaz de segurar a carga em dias frios", "substituição da bateria", 400],
    ["Troca de bateria como parte da manutenção regular", "troca preventiva de bateria", 380],
    ["Bateria não suporta carga após desligamento do motor", "troca de bateria com revisão completa", 420],
    ["Luzes do painel acendem por um instante mas o motor não liga", "troca de bateria com revisão completa", 420]
]
